/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LunaApi);
  }
}(this, function(expect, LunaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LunaApi.ApplicationConfigurationDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApplicationConfigurationDto', function() {
    it('should create an instance of ApplicationConfigurationDto', function() {
      // uncomment below and update the code to test ApplicationConfigurationDto
      //var instance = new LunaApi.ApplicationConfigurationDto();
      //expect(instance).to.be.a(LunaApi.ApplicationConfigurationDto);
    });

    it('should have the property localization (base name: "localization")', function() {
      // uncomment below and update the code to test the property localization
      //var instance = new LunaApi.ApplicationConfigurationDto();
      //expect(instance).to.be();
    });

    it('should have the property auth (base name: "auth")', function() {
      // uncomment below and update the code to test the property auth
      //var instance = new LunaApi.ApplicationConfigurationDto();
      //expect(instance).to.be();
    });

    it('should have the property setting (base name: "setting")', function() {
      // uncomment below and update the code to test the property setting
      //var instance = new LunaApi.ApplicationConfigurationDto();
      //expect(instance).to.be();
    });

    it('should have the property currentUser (base name: "currentUser")', function() {
      // uncomment below and update the code to test the property currentUser
      //var instance = new LunaApi.ApplicationConfigurationDto();
      //expect(instance).to.be();
    });

    it('should have the property features (base name: "features")', function() {
      // uncomment below and update the code to test the property features
      //var instance = new LunaApi.ApplicationConfigurationDto();
      //expect(instance).to.be();
    });

    it('should have the property globalFeatures (base name: "globalFeatures")', function() {
      // uncomment below and update the code to test the property globalFeatures
      //var instance = new LunaApi.ApplicationConfigurationDto();
      //expect(instance).to.be();
    });

    it('should have the property multiTenancy (base name: "multiTenancy")', function() {
      // uncomment below and update the code to test the property multiTenancy
      //var instance = new LunaApi.ApplicationConfigurationDto();
      //expect(instance).to.be();
    });

    it('should have the property currentTenant (base name: "currentTenant")', function() {
      // uncomment below and update the code to test the property currentTenant
      //var instance = new LunaApi.ApplicationConfigurationDto();
      //expect(instance).to.be();
    });

    it('should have the property timing (base name: "timing")', function() {
      // uncomment below and update the code to test the property timing
      //var instance = new LunaApi.ApplicationConfigurationDto();
      //expect(instance).to.be();
    });

    it('should have the property clock (base name: "clock")', function() {
      // uncomment below and update the code to test the property clock
      //var instance = new LunaApi.ApplicationConfigurationDto();
      //expect(instance).to.be();
    });

    it('should have the property objectExtensions (base name: "objectExtensions")', function() {
      // uncomment below and update the code to test the property objectExtensions
      //var instance = new LunaApi.ApplicationConfigurationDto();
      //expect(instance).to.be();
    });

    it('should have the property extraProperties (base name: "extraProperties")', function() {
      // uncomment below and update the code to test the property extraProperties
      //var instance = new LunaApi.ApplicationConfigurationDto();
      //expect(instance).to.be();
    });

  });

}));
