/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LunaApi);
  }
}(this, function(expect, LunaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LunaApi.ApplicationLocalizationConfigurationDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApplicationLocalizationConfigurationDto', function() {
    it('should create an instance of ApplicationLocalizationConfigurationDto', function() {
      // uncomment below and update the code to test ApplicationLocalizationConfigurationDto
      //var instance = new LunaApi.ApplicationLocalizationConfigurationDto();
      //expect(instance).to.be.a(LunaApi.ApplicationLocalizationConfigurationDto);
    });

    it('should have the property values (base name: "values")', function() {
      // uncomment below and update the code to test the property values
      //var instance = new LunaApi.ApplicationLocalizationConfigurationDto();
      //expect(instance).to.be();
    });

    it('should have the property languages (base name: "languages")', function() {
      // uncomment below and update the code to test the property languages
      //var instance = new LunaApi.ApplicationLocalizationConfigurationDto();
      //expect(instance).to.be();
    });

    it('should have the property currentCulture (base name: "currentCulture")', function() {
      // uncomment below and update the code to test the property currentCulture
      //var instance = new LunaApi.ApplicationLocalizationConfigurationDto();
      //expect(instance).to.be();
    });

    it('should have the property defaultResourceName (base name: "defaultResourceName")', function() {
      // uncomment below and update the code to test the property defaultResourceName
      //var instance = new LunaApi.ApplicationLocalizationConfigurationDto();
      //expect(instance).to.be();
    });

    it('should have the property languagesMap (base name: "languagesMap")', function() {
      // uncomment below and update the code to test the property languagesMap
      //var instance = new LunaApi.ApplicationLocalizationConfigurationDto();
      //expect(instance).to.be();
    });

    it('should have the property languageFilesMap (base name: "languageFilesMap")', function() {
      // uncomment below and update the code to test the property languageFilesMap
      //var instance = new LunaApi.ApplicationLocalizationConfigurationDto();
      //expect(instance).to.be();
    });

  });

}));
