/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LunaApi);
  }
}(this, function(expect, LunaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LunaApi.ControllerApiDescriptionModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ControllerApiDescriptionModel', function() {
    it('should create an instance of ControllerApiDescriptionModel', function() {
      // uncomment below and update the code to test ControllerApiDescriptionModel
      //var instance = new LunaApi.ControllerApiDescriptionModel();
      //expect(instance).to.be.a(LunaApi.ControllerApiDescriptionModel);
    });

    it('should have the property controllerName (base name: "controllerName")', function() {
      // uncomment below and update the code to test the property controllerName
      //var instance = new LunaApi.ControllerApiDescriptionModel();
      //expect(instance).to.be();
    });

    it('should have the property controllerGroupName (base name: "controllerGroupName")', function() {
      // uncomment below and update the code to test the property controllerGroupName
      //var instance = new LunaApi.ControllerApiDescriptionModel();
      //expect(instance).to.be();
    });

    it('should have the property isRemoteService (base name: "isRemoteService")', function() {
      // uncomment below and update the code to test the property isRemoteService
      //var instance = new LunaApi.ControllerApiDescriptionModel();
      //expect(instance).to.be();
    });

    it('should have the property apiVersion (base name: "apiVersion")', function() {
      // uncomment below and update the code to test the property apiVersion
      //var instance = new LunaApi.ControllerApiDescriptionModel();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new LunaApi.ControllerApiDescriptionModel();
      //expect(instance).to.be();
    });

    it('should have the property interfaces (base name: "interfaces")', function() {
      // uncomment below and update the code to test the property interfaces
      //var instance = new LunaApi.ControllerApiDescriptionModel();
      //expect(instance).to.be();
    });

    it('should have the property actions (base name: "actions")', function() {
      // uncomment below and update the code to test the property actions
      //var instance = new LunaApi.ControllerApiDescriptionModel();
      //expect(instance).to.be();
    });

  });

}));
