/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LunaApi);
  }
}(this, function(expect, LunaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LunaApi.CurrentCultureDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CurrentCultureDto', function() {
    it('should create an instance of CurrentCultureDto', function() {
      // uncomment below and update the code to test CurrentCultureDto
      //var instance = new LunaApi.CurrentCultureDto();
      //expect(instance).to.be.a(LunaApi.CurrentCultureDto);
    });

    it('should have the property displayName (base name: "displayName")', function() {
      // uncomment below and update the code to test the property displayName
      //var instance = new LunaApi.CurrentCultureDto();
      //expect(instance).to.be();
    });

    it('should have the property englishName (base name: "englishName")', function() {
      // uncomment below and update the code to test the property englishName
      //var instance = new LunaApi.CurrentCultureDto();
      //expect(instance).to.be();
    });

    it('should have the property threeLetterIsoLanguageName (base name: "threeLetterIsoLanguageName")', function() {
      // uncomment below and update the code to test the property threeLetterIsoLanguageName
      //var instance = new LunaApi.CurrentCultureDto();
      //expect(instance).to.be();
    });

    it('should have the property twoLetterIsoLanguageName (base name: "twoLetterIsoLanguageName")', function() {
      // uncomment below and update the code to test the property twoLetterIsoLanguageName
      //var instance = new LunaApi.CurrentCultureDto();
      //expect(instance).to.be();
    });

    it('should have the property isRightToLeft (base name: "isRightToLeft")', function() {
      // uncomment below and update the code to test the property isRightToLeft
      //var instance = new LunaApi.CurrentCultureDto();
      //expect(instance).to.be();
    });

    it('should have the property cultureName (base name: "cultureName")', function() {
      // uncomment below and update the code to test the property cultureName
      //var instance = new LunaApi.CurrentCultureDto();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new LunaApi.CurrentCultureDto();
      //expect(instance).to.be();
    });

    it('should have the property nativeName (base name: "nativeName")', function() {
      // uncomment below and update the code to test the property nativeName
      //var instance = new LunaApi.CurrentCultureDto();
      //expect(instance).to.be();
    });

    it('should have the property dateTimeFormat (base name: "dateTimeFormat")', function() {
      // uncomment below and update the code to test the property dateTimeFormat
      //var instance = new LunaApi.CurrentCultureDto();
      //expect(instance).to.be();
    });

  });

}));
