/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LunaApi);
  }
}(this, function(expect, LunaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LunaApi.DateTimeFormatDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DateTimeFormatDto', function() {
    it('should create an instance of DateTimeFormatDto', function() {
      // uncomment below and update the code to test DateTimeFormatDto
      //var instance = new LunaApi.DateTimeFormatDto();
      //expect(instance).to.be.a(LunaApi.DateTimeFormatDto);
    });

    it('should have the property calendarAlgorithmType (base name: "calendarAlgorithmType")', function() {
      // uncomment below and update the code to test the property calendarAlgorithmType
      //var instance = new LunaApi.DateTimeFormatDto();
      //expect(instance).to.be();
    });

    it('should have the property dateTimeFormatLong (base name: "dateTimeFormatLong")', function() {
      // uncomment below and update the code to test the property dateTimeFormatLong
      //var instance = new LunaApi.DateTimeFormatDto();
      //expect(instance).to.be();
    });

    it('should have the property shortDatePattern (base name: "shortDatePattern")', function() {
      // uncomment below and update the code to test the property shortDatePattern
      //var instance = new LunaApi.DateTimeFormatDto();
      //expect(instance).to.be();
    });

    it('should have the property fullDateTimePattern (base name: "fullDateTimePattern")', function() {
      // uncomment below and update the code to test the property fullDateTimePattern
      //var instance = new LunaApi.DateTimeFormatDto();
      //expect(instance).to.be();
    });

    it('should have the property dateSeparator (base name: "dateSeparator")', function() {
      // uncomment below and update the code to test the property dateSeparator
      //var instance = new LunaApi.DateTimeFormatDto();
      //expect(instance).to.be();
    });

    it('should have the property shortTimePattern (base name: "shortTimePattern")', function() {
      // uncomment below and update the code to test the property shortTimePattern
      //var instance = new LunaApi.DateTimeFormatDto();
      //expect(instance).to.be();
    });

    it('should have the property longTimePattern (base name: "longTimePattern")', function() {
      // uncomment below and update the code to test the property longTimePattern
      //var instance = new LunaApi.DateTimeFormatDto();
      //expect(instance).to.be();
    });

  });

}));
