/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LunaApi);
  }
}(this, function(expect, LunaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LunaApi.EmailSettingsDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EmailSettingsDto', function() {
    it('should create an instance of EmailSettingsDto', function() {
      // uncomment below and update the code to test EmailSettingsDto
      //var instance = new LunaApi.EmailSettingsDto();
      //expect(instance).to.be.a(LunaApi.EmailSettingsDto);
    });

    it('should have the property smtpHost (base name: "smtpHost")', function() {
      // uncomment below and update the code to test the property smtpHost
      //var instance = new LunaApi.EmailSettingsDto();
      //expect(instance).to.be();
    });

    it('should have the property smtpPort (base name: "smtpPort")', function() {
      // uncomment below and update the code to test the property smtpPort
      //var instance = new LunaApi.EmailSettingsDto();
      //expect(instance).to.be();
    });

    it('should have the property smtpUserName (base name: "smtpUserName")', function() {
      // uncomment below and update the code to test the property smtpUserName
      //var instance = new LunaApi.EmailSettingsDto();
      //expect(instance).to.be();
    });

    it('should have the property smtpPassword (base name: "smtpPassword")', function() {
      // uncomment below and update the code to test the property smtpPassword
      //var instance = new LunaApi.EmailSettingsDto();
      //expect(instance).to.be();
    });

    it('should have the property smtpDomain (base name: "smtpDomain")', function() {
      // uncomment below and update the code to test the property smtpDomain
      //var instance = new LunaApi.EmailSettingsDto();
      //expect(instance).to.be();
    });

    it('should have the property smtpEnableSsl (base name: "smtpEnableSsl")', function() {
      // uncomment below and update the code to test the property smtpEnableSsl
      //var instance = new LunaApi.EmailSettingsDto();
      //expect(instance).to.be();
    });

    it('should have the property smtpUseDefaultCredentials (base name: "smtpUseDefaultCredentials")', function() {
      // uncomment below and update the code to test the property smtpUseDefaultCredentials
      //var instance = new LunaApi.EmailSettingsDto();
      //expect(instance).to.be();
    });

    it('should have the property defaultFromAddress (base name: "defaultFromAddress")', function() {
      // uncomment below and update the code to test the property defaultFromAddress
      //var instance = new LunaApi.EmailSettingsDto();
      //expect(instance).to.be();
    });

    it('should have the property defaultFromDisplayName (base name: "defaultFromDisplayName")', function() {
      // uncomment below and update the code to test the property defaultFromDisplayName
      //var instance = new LunaApi.EmailSettingsDto();
      //expect(instance).to.be();
    });

  });

}));
