/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LunaApi);
  }
}(this, function(expect, LunaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LunaApi.FeatureDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FeatureDto', function() {
    it('should create an instance of FeatureDto', function() {
      // uncomment below and update the code to test FeatureDto
      //var instance = new LunaApi.FeatureDto();
      //expect(instance).to.be.a(LunaApi.FeatureDto);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new LunaApi.FeatureDto();
      //expect(instance).to.be();
    });

    it('should have the property displayName (base name: "displayName")', function() {
      // uncomment below and update the code to test the property displayName
      //var instance = new LunaApi.FeatureDto();
      //expect(instance).to.be();
    });

    it('should have the property value (base name: "value")', function() {
      // uncomment below and update the code to test the property value
      //var instance = new LunaApi.FeatureDto();
      //expect(instance).to.be();
    });

    it('should have the property provider (base name: "provider")', function() {
      // uncomment below and update the code to test the property provider
      //var instance = new LunaApi.FeatureDto();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new LunaApi.FeatureDto();
      //expect(instance).to.be();
    });

    it('should have the property valueType (base name: "valueType")', function() {
      // uncomment below and update the code to test the property valueType
      //var instance = new LunaApi.FeatureDto();
      //expect(instance).to.be();
    });

    it('should have the property depth (base name: "depth")', function() {
      // uncomment below and update the code to test the property depth
      //var instance = new LunaApi.FeatureDto();
      //expect(instance).to.be();
    });

    it('should have the property parentName (base name: "parentName")', function() {
      // uncomment below and update the code to test the property parentName
      //var instance = new LunaApi.FeatureDto();
      //expect(instance).to.be();
    });

  });

}));
