/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LunaApi);
  }
}(this, function(expect, LunaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LunaApi.ParameterApiDescriptionModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ParameterApiDescriptionModel', function() {
    it('should create an instance of ParameterApiDescriptionModel', function() {
      // uncomment below and update the code to test ParameterApiDescriptionModel
      //var instance = new LunaApi.ParameterApiDescriptionModel();
      //expect(instance).to.be.a(LunaApi.ParameterApiDescriptionModel);
    });

    it('should have the property nameOnMethod (base name: "nameOnMethod")', function() {
      // uncomment below and update the code to test the property nameOnMethod
      //var instance = new LunaApi.ParameterApiDescriptionModel();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new LunaApi.ParameterApiDescriptionModel();
      //expect(instance).to.be();
    });

    it('should have the property jsonName (base name: "jsonName")', function() {
      // uncomment below and update the code to test the property jsonName
      //var instance = new LunaApi.ParameterApiDescriptionModel();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new LunaApi.ParameterApiDescriptionModel();
      //expect(instance).to.be();
    });

    it('should have the property typeSimple (base name: "typeSimple")', function() {
      // uncomment below and update the code to test the property typeSimple
      //var instance = new LunaApi.ParameterApiDescriptionModel();
      //expect(instance).to.be();
    });

    it('should have the property isOptional (base name: "isOptional")', function() {
      // uncomment below and update the code to test the property isOptional
      //var instance = new LunaApi.ParameterApiDescriptionModel();
      //expect(instance).to.be();
    });

    it('should have the property defaultValue (base name: "defaultValue")', function() {
      // uncomment below and update the code to test the property defaultValue
      //var instance = new LunaApi.ParameterApiDescriptionModel();
      //expect(instance).to.be();
    });

    it('should have the property constraintTypes (base name: "constraintTypes")', function() {
      // uncomment below and update the code to test the property constraintTypes
      //var instance = new LunaApi.ParameterApiDescriptionModel();
      //expect(instance).to.be();
    });

    it('should have the property bindingSourceId (base name: "bindingSourceId")', function() {
      // uncomment below and update the code to test the property bindingSourceId
      //var instance = new LunaApi.ParameterApiDescriptionModel();
      //expect(instance).to.be();
    });

    it('should have the property descriptorName (base name: "descriptorName")', function() {
      // uncomment below and update the code to test the property descriptorName
      //var instance = new LunaApi.ParameterApiDescriptionModel();
      //expect(instance).to.be();
    });

  });

}));
