/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LunaApi);
  }
}(this, function(expect, LunaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LunaApi.PermissionGrantInfoDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PermissionGrantInfoDto', function() {
    it('should create an instance of PermissionGrantInfoDto', function() {
      // uncomment below and update the code to test PermissionGrantInfoDto
      //var instance = new LunaApi.PermissionGrantInfoDto();
      //expect(instance).to.be.a(LunaApi.PermissionGrantInfoDto);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new LunaApi.PermissionGrantInfoDto();
      //expect(instance).to.be();
    });

    it('should have the property displayName (base name: "displayName")', function() {
      // uncomment below and update the code to test the property displayName
      //var instance = new LunaApi.PermissionGrantInfoDto();
      //expect(instance).to.be();
    });

    it('should have the property parentName (base name: "parentName")', function() {
      // uncomment below and update the code to test the property parentName
      //var instance = new LunaApi.PermissionGrantInfoDto();
      //expect(instance).to.be();
    });

    it('should have the property isGranted (base name: "isGranted")', function() {
      // uncomment below and update the code to test the property isGranted
      //var instance = new LunaApi.PermissionGrantInfoDto();
      //expect(instance).to.be();
    });

    it('should have the property allowedProviders (base name: "allowedProviders")', function() {
      // uncomment below and update the code to test the property allowedProviders
      //var instance = new LunaApi.PermissionGrantInfoDto();
      //expect(instance).to.be();
    });

    it('should have the property grantedProviders (base name: "grantedProviders")', function() {
      // uncomment below and update the code to test the property grantedProviders
      //var instance = new LunaApi.PermissionGrantInfoDto();
      //expect(instance).to.be();
    });

  });

}));
