/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LunaApi);
  }
}(this, function(expect, LunaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LunaApi.SendTestEmailInput();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SendTestEmailInput', function() {
    it('should create an instance of SendTestEmailInput', function() {
      // uncomment below and update the code to test SendTestEmailInput
      //var instance = new LunaApi.SendTestEmailInput();
      //expect(instance).to.be.a(LunaApi.SendTestEmailInput);
    });

    it('should have the property senderEmailAddress (base name: "senderEmailAddress")', function() {
      // uncomment below and update the code to test the property senderEmailAddress
      //var instance = new LunaApi.SendTestEmailInput();
      //expect(instance).to.be();
    });

    it('should have the property targetEmailAddress (base name: "targetEmailAddress")', function() {
      // uncomment below and update the code to test the property targetEmailAddress
      //var instance = new LunaApi.SendTestEmailInput();
      //expect(instance).to.be();
    });

    it('should have the property subject (base name: "subject")', function() {
      // uncomment below and update the code to test the property subject
      //var instance = new LunaApi.SendTestEmailInput();
      //expect(instance).to.be();
    });

    it('should have the property body (base name: "body")', function() {
      // uncomment below and update the code to test the property body
      //var instance = new LunaApi.SendTestEmailInput();
      //expect(instance).to.be();
    });

  });

}));
