/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ApplicationConfigurationDto from '../model/ApplicationConfigurationDto';
import RemoteServiceErrorResponse from '../model/RemoteServiceErrorResponse';

/**
* AbpApplicationConfiguration service.
* @module api/AbpApplicationConfigurationApi
* @version v1
*/
export default class AbpApplicationConfigurationApi {

    /**
    * Constructs a new AbpApplicationConfigurationApi. 
    * @alias module:api/AbpApplicationConfigurationApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the abpApplicationConfigurationGet operation.
     * @callback module:api/AbpApplicationConfigurationApi~abpApplicationConfigurationGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ApplicationConfigurationDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/AbpApplicationConfigurationApi~abpApplicationConfigurationGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ApplicationConfigurationDto}
     */
    abpApplicationConfigurationGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = ApplicationConfigurationDto;
      return this.apiClient.callApi(
        '/api/abp/application-configuration', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
