/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AbpLoginResult from '../model/AbpLoginResult';
import RemoteServiceErrorResponse from '../model/RemoteServiceErrorResponse';
import UserLoginInfo from '../model/UserLoginInfo';

/**
* Login service.
* @module api/LoginApi
* @version v1
*/
export default class LoginApi {

    /**
    * Constructs a new LoginApi. 
    * @alias module:api/LoginApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the loginCheckPassword operation.
     * @callback module:api/LoginApi~loginCheckPasswordCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AbpLoginResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {module:model/UserLoginInfo} opts.userLoginInfo 
     * @param {module:api/LoginApi~loginCheckPasswordCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AbpLoginResult}
     */
    loginCheckPassword(opts, callback) {
      opts = opts || {};
      let postBody = opts['userLoginInfo'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json', 'text/json', 'application/*+json'];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = AbpLoginResult;
      return this.apiClient.callApi(
        '/api/account/check-password', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the loginLogin operation.
     * @callback module:api/LoginApi~loginLoginCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AbpLoginResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {module:model/UserLoginInfo} opts.userLoginInfo 
     * @param {module:api/LoginApi~loginLoginCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AbpLoginResult}
     */
    loginLogin(opts, callback) {
      opts = opts || {};
      let postBody = opts['userLoginInfo'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json', 'text/json', 'application/*+json'];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = AbpLoginResult;
      return this.apiClient.callApi(
        '/api/account/login', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the loginLogout operation.
     * @callback module:api/LoginApi~loginLogoutCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/LoginApi~loginLogoutCallback} callback The callback function, accepting three arguments: error, data, response
     */
    loginLogout(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/account/logout', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
