/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MethodParameterApiDescriptionModel from './MethodParameterApiDescriptionModel';
import ParameterApiDescriptionModel from './ParameterApiDescriptionModel';
import ReturnValueApiDescriptionModel from './ReturnValueApiDescriptionModel';

/**
 * The ActionApiDescriptionModel model module.
 * @module model/ActionApiDescriptionModel
 * @version v1
 */
class ActionApiDescriptionModel {
    /**
     * Constructs a new <code>ActionApiDescriptionModel</code>.
     * @alias module:model/ActionApiDescriptionModel
     */
    constructor() { 
        
        ActionApiDescriptionModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ActionApiDescriptionModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ActionApiDescriptionModel} obj Optional instance to populate.
     * @return {module:model/ActionApiDescriptionModel} The populated <code>ActionApiDescriptionModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActionApiDescriptionModel();

            if (data.hasOwnProperty('uniqueName')) {
                obj['uniqueName'] = ApiClient.convertToType(data['uniqueName'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('httpMethod')) {
                obj['httpMethod'] = ApiClient.convertToType(data['httpMethod'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('supportedVersions')) {
                obj['supportedVersions'] = ApiClient.convertToType(data['supportedVersions'], ['String']);
            }
            if (data.hasOwnProperty('parametersOnMethod')) {
                obj['parametersOnMethod'] = ApiClient.convertToType(data['parametersOnMethod'], [MethodParameterApiDescriptionModel]);
            }
            if (data.hasOwnProperty('parameters')) {
                obj['parameters'] = ApiClient.convertToType(data['parameters'], [ParameterApiDescriptionModel]);
            }
            if (data.hasOwnProperty('returnValue')) {
                obj['returnValue'] = ReturnValueApiDescriptionModel.constructFromObject(data['returnValue']);
            }
            if (data.hasOwnProperty('allowAnonymous')) {
                obj['allowAnonymous'] = ApiClient.convertToType(data['allowAnonymous'], 'Boolean');
            }
            if (data.hasOwnProperty('implementFrom')) {
                obj['implementFrom'] = ApiClient.convertToType(data['implementFrom'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} uniqueName
 */
ActionApiDescriptionModel.prototype['uniqueName'] = undefined;

/**
 * @member {String} name
 */
ActionApiDescriptionModel.prototype['name'] = undefined;

/**
 * @member {String} httpMethod
 */
ActionApiDescriptionModel.prototype['httpMethod'] = undefined;

/**
 * @member {String} url
 */
ActionApiDescriptionModel.prototype['url'] = undefined;

/**
 * @member {Array.<String>} supportedVersions
 */
ActionApiDescriptionModel.prototype['supportedVersions'] = undefined;

/**
 * @member {Array.<module:model/MethodParameterApiDescriptionModel>} parametersOnMethod
 */
ActionApiDescriptionModel.prototype['parametersOnMethod'] = undefined;

/**
 * @member {Array.<module:model/ParameterApiDescriptionModel>} parameters
 */
ActionApiDescriptionModel.prototype['parameters'] = undefined;

/**
 * @member {module:model/ReturnValueApiDescriptionModel} returnValue
 */
ActionApiDescriptionModel.prototype['returnValue'] = undefined;

/**
 * @member {Boolean} allowAnonymous
 */
ActionApiDescriptionModel.prototype['allowAnonymous'] = undefined;

/**
 * @member {String} implementFrom
 */
ActionApiDescriptionModel.prototype['implementFrom'] = undefined;






export default ActionApiDescriptionModel;

