/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApplicationFeatureConfigurationDto model module.
 * @module model/ApplicationFeatureConfigurationDto
 * @version v1
 */
class ApplicationFeatureConfigurationDto {
    /**
     * Constructs a new <code>ApplicationFeatureConfigurationDto</code>.
     * @alias module:model/ApplicationFeatureConfigurationDto
     */
    constructor() { 
        
        ApplicationFeatureConfigurationDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApplicationFeatureConfigurationDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApplicationFeatureConfigurationDto} obj Optional instance to populate.
     * @return {module:model/ApplicationFeatureConfigurationDto} The populated <code>ApplicationFeatureConfigurationDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApplicationFeatureConfigurationDto();

            if (data.hasOwnProperty('values')) {
                obj['values'] = ApiClient.convertToType(data['values'], {'String': 'String'});
            }
        }
        return obj;
    }


}

/**
 * @member {Object.<String, String>} values
 */
ApplicationFeatureConfigurationDto.prototype['values'] = undefined;






export default ApplicationFeatureConfigurationDto;

