/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ModuleApiDescriptionModel from './ModuleApiDescriptionModel';
import TypeApiDescriptionModel from './TypeApiDescriptionModel';

/**
 * The ApplicationApiDescriptionModel model module.
 * @module model/ApplicationApiDescriptionModel
 * @version v1
 */
class ApplicationApiDescriptionModel {
    /**
     * Constructs a new <code>ApplicationApiDescriptionModel</code>.
     * @alias module:model/ApplicationApiDescriptionModel
     */
    constructor() { 
        
        ApplicationApiDescriptionModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApplicationApiDescriptionModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApplicationApiDescriptionModel} obj Optional instance to populate.
     * @return {module:model/ApplicationApiDescriptionModel} The populated <code>ApplicationApiDescriptionModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApplicationApiDescriptionModel();

            if (data.hasOwnProperty('modules')) {
                obj['modules'] = ApiClient.convertToType(data['modules'], {'String': ModuleApiDescriptionModel});
            }
            if (data.hasOwnProperty('types')) {
                obj['types'] = ApiClient.convertToType(data['types'], {'String': TypeApiDescriptionModel});
            }
        }
        return obj;
    }


}

/**
 * @member {Object.<String, module:model/ModuleApiDescriptionModel>} modules
 */
ApplicationApiDescriptionModel.prototype['modules'] = undefined;

/**
 * @member {Object.<String, module:model/TypeApiDescriptionModel>} types
 */
ApplicationApiDescriptionModel.prototype['types'] = undefined;






export default ApplicationApiDescriptionModel;

