/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApplicationGlobalFeatureConfigurationDto model module.
 * @module model/ApplicationGlobalFeatureConfigurationDto
 * @version v1
 */
class ApplicationGlobalFeatureConfigurationDto {
    /**
     * Constructs a new <code>ApplicationGlobalFeatureConfigurationDto</code>.
     * @alias module:model/ApplicationGlobalFeatureConfigurationDto
     */
    constructor() { 
        
        ApplicationGlobalFeatureConfigurationDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApplicationGlobalFeatureConfigurationDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApplicationGlobalFeatureConfigurationDto} obj Optional instance to populate.
     * @return {module:model/ApplicationGlobalFeatureConfigurationDto} The populated <code>ApplicationGlobalFeatureConfigurationDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApplicationGlobalFeatureConfigurationDto();

            if (data.hasOwnProperty('enabledFeatures')) {
                obj['enabledFeatures'] = ApiClient.convertToType(data['enabledFeatures'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} enabledFeatures
 */
ApplicationGlobalFeatureConfigurationDto.prototype['enabledFeatures'] = undefined;






export default ApplicationGlobalFeatureConfigurationDto;

