/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApplicationAuthConfigurationDto model module.
 * @module model/ApplicationAuthConfigurationDto
 * @version v1
 */
class ApplicationAuthConfigurationDto {
    /**
     * Constructs a new <code>ApplicationAuthConfigurationDto</code>.
     * @alias module:model/ApplicationAuthConfigurationDto
     */
    constructor() { 
        
        ApplicationAuthConfigurationDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApplicationAuthConfigurationDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApplicationAuthConfigurationDto} obj Optional instance to populate.
     * @return {module:model/ApplicationAuthConfigurationDto} The populated <code>ApplicationAuthConfigurationDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApplicationAuthConfigurationDto();

            if (data.hasOwnProperty('policies')) {
                obj['policies'] = ApiClient.convertToType(data['policies'], {'String': 'Boolean'});
            }
            if (data.hasOwnProperty('grantedPolicies')) {
                obj['grantedPolicies'] = ApiClient.convertToType(data['grantedPolicies'], {'String': 'Boolean'});
            }
        }
        return obj;
    }


}

/**
 * @member {Object.<String, Boolean>} policies
 */
ApplicationAuthConfigurationDto.prototype['policies'] = undefined;

/**
 * @member {Object.<String, Boolean>} grantedPolicies
 */
ApplicationAuthConfigurationDto.prototype['grantedPolicies'] = undefined;






export default ApplicationAuthConfigurationDto;

