/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ChangePasswordInput model module.
 * @module model/ChangePasswordInput
 * @version v1
 */
class ChangePasswordInput {
    /**
     * Constructs a new <code>ChangePasswordInput</code>.
     * @alias module:model/ChangePasswordInput
     * @param newPassword {String} 
     */
    constructor(newPassword) { 
        
        ChangePasswordInput.initialize(this, newPassword);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, newPassword) { 
        obj['newPassword'] = newPassword;
    }

    /**
     * Constructs a <code>ChangePasswordInput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChangePasswordInput} obj Optional instance to populate.
     * @return {module:model/ChangePasswordInput} The populated <code>ChangePasswordInput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChangePasswordInput();

            if (data.hasOwnProperty('currentPassword')) {
                obj['currentPassword'] = ApiClient.convertToType(data['currentPassword'], 'String');
            }
            if (data.hasOwnProperty('newPassword')) {
                obj['newPassword'] = ApiClient.convertToType(data['newPassword'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} currentPassword
 */
ChangePasswordInput.prototype['currentPassword'] = undefined;

/**
 * @member {String} newPassword
 */
ChangePasswordInput.prototype['newPassword'] = undefined;






export default ChangePasswordInput;

