/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ControllerInterfaceApiDescriptionModel model module.
 * @module model/ControllerInterfaceApiDescriptionModel
 * @version v1
 */
class ControllerInterfaceApiDescriptionModel {
    /**
     * Constructs a new <code>ControllerInterfaceApiDescriptionModel</code>.
     * @alias module:model/ControllerInterfaceApiDescriptionModel
     */
    constructor() { 
        
        ControllerInterfaceApiDescriptionModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ControllerInterfaceApiDescriptionModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ControllerInterfaceApiDescriptionModel} obj Optional instance to populate.
     * @return {module:model/ControllerInterfaceApiDescriptionModel} The populated <code>ControllerInterfaceApiDescriptionModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ControllerInterfaceApiDescriptionModel();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} type
 */
ControllerInterfaceApiDescriptionModel.prototype['type'] = undefined;






export default ControllerInterfaceApiDescriptionModel;

