/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DateTimeFormatDto from './DateTimeFormatDto';

/**
 * The CurrentCultureDto model module.
 * @module model/CurrentCultureDto
 * @version v1
 */
class CurrentCultureDto {
    /**
     * Constructs a new <code>CurrentCultureDto</code>.
     * @alias module:model/CurrentCultureDto
     */
    constructor() { 
        
        CurrentCultureDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CurrentCultureDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CurrentCultureDto} obj Optional instance to populate.
     * @return {module:model/CurrentCultureDto} The populated <code>CurrentCultureDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CurrentCultureDto();

            if (data.hasOwnProperty('displayName')) {
                obj['displayName'] = ApiClient.convertToType(data['displayName'], 'String');
            }
            if (data.hasOwnProperty('englishName')) {
                obj['englishName'] = ApiClient.convertToType(data['englishName'], 'String');
            }
            if (data.hasOwnProperty('threeLetterIsoLanguageName')) {
                obj['threeLetterIsoLanguageName'] = ApiClient.convertToType(data['threeLetterIsoLanguageName'], 'String');
            }
            if (data.hasOwnProperty('twoLetterIsoLanguageName')) {
                obj['twoLetterIsoLanguageName'] = ApiClient.convertToType(data['twoLetterIsoLanguageName'], 'String');
            }
            if (data.hasOwnProperty('isRightToLeft')) {
                obj['isRightToLeft'] = ApiClient.convertToType(data['isRightToLeft'], 'Boolean');
            }
            if (data.hasOwnProperty('cultureName')) {
                obj['cultureName'] = ApiClient.convertToType(data['cultureName'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('nativeName')) {
                obj['nativeName'] = ApiClient.convertToType(data['nativeName'], 'String');
            }
            if (data.hasOwnProperty('dateTimeFormat')) {
                obj['dateTimeFormat'] = DateTimeFormatDto.constructFromObject(data['dateTimeFormat']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} displayName
 */
CurrentCultureDto.prototype['displayName'] = undefined;

/**
 * @member {String} englishName
 */
CurrentCultureDto.prototype['englishName'] = undefined;

/**
 * @member {String} threeLetterIsoLanguageName
 */
CurrentCultureDto.prototype['threeLetterIsoLanguageName'] = undefined;

/**
 * @member {String} twoLetterIsoLanguageName
 */
CurrentCultureDto.prototype['twoLetterIsoLanguageName'] = undefined;

/**
 * @member {Boolean} isRightToLeft
 */
CurrentCultureDto.prototype['isRightToLeft'] = undefined;

/**
 * @member {String} cultureName
 */
CurrentCultureDto.prototype['cultureName'] = undefined;

/**
 * @member {String} name
 */
CurrentCultureDto.prototype['name'] = undefined;

/**
 * @member {String} nativeName
 */
CurrentCultureDto.prototype['nativeName'] = undefined;

/**
 * @member {module:model/DateTimeFormatDto} dateTimeFormat
 */
CurrentCultureDto.prototype['dateTimeFormat'] = undefined;






export default CurrentCultureDto;

