/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CurrentTenantDto model module.
 * @module model/CurrentTenantDto
 * @version v1
 */
class CurrentTenantDto {
    /**
     * Constructs a new <code>CurrentTenantDto</code>.
     * @alias module:model/CurrentTenantDto
     */
    constructor() { 
        
        CurrentTenantDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CurrentTenantDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CurrentTenantDto} obj Optional instance to populate.
     * @return {module:model/CurrentTenantDto} The populated <code>CurrentTenantDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CurrentTenantDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('isAvailable')) {
                obj['isAvailable'] = ApiClient.convertToType(data['isAvailable'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
CurrentTenantDto.prototype['id'] = undefined;

/**
 * @member {String} name
 */
CurrentTenantDto.prototype['name'] = undefined;

/**
 * @member {Boolean} isAvailable
 */
CurrentTenantDto.prototype['isAvailable'] = undefined;






export default CurrentTenantDto;

