/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EmailSettingsDto model module.
 * @module model/EmailSettingsDto
 * @version v1
 */
class EmailSettingsDto {
    /**
     * Constructs a new <code>EmailSettingsDto</code>.
     * @alias module:model/EmailSettingsDto
     */
    constructor() { 
        
        EmailSettingsDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EmailSettingsDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EmailSettingsDto} obj Optional instance to populate.
     * @return {module:model/EmailSettingsDto} The populated <code>EmailSettingsDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmailSettingsDto();

            if (data.hasOwnProperty('smtpHost')) {
                obj['smtpHost'] = ApiClient.convertToType(data['smtpHost'], 'String');
            }
            if (data.hasOwnProperty('smtpPort')) {
                obj['smtpPort'] = ApiClient.convertToType(data['smtpPort'], 'Number');
            }
            if (data.hasOwnProperty('smtpUserName')) {
                obj['smtpUserName'] = ApiClient.convertToType(data['smtpUserName'], 'String');
            }
            if (data.hasOwnProperty('smtpPassword')) {
                obj['smtpPassword'] = ApiClient.convertToType(data['smtpPassword'], 'String');
            }
            if (data.hasOwnProperty('smtpDomain')) {
                obj['smtpDomain'] = ApiClient.convertToType(data['smtpDomain'], 'String');
            }
            if (data.hasOwnProperty('smtpEnableSsl')) {
                obj['smtpEnableSsl'] = ApiClient.convertToType(data['smtpEnableSsl'], 'Boolean');
            }
            if (data.hasOwnProperty('smtpUseDefaultCredentials')) {
                obj['smtpUseDefaultCredentials'] = ApiClient.convertToType(data['smtpUseDefaultCredentials'], 'Boolean');
            }
            if (data.hasOwnProperty('defaultFromAddress')) {
                obj['defaultFromAddress'] = ApiClient.convertToType(data['defaultFromAddress'], 'String');
            }
            if (data.hasOwnProperty('defaultFromDisplayName')) {
                obj['defaultFromDisplayName'] = ApiClient.convertToType(data['defaultFromDisplayName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} smtpHost
 */
EmailSettingsDto.prototype['smtpHost'] = undefined;

/**
 * @member {Number} smtpPort
 */
EmailSettingsDto.prototype['smtpPort'] = undefined;

/**
 * @member {String} smtpUserName
 */
EmailSettingsDto.prototype['smtpUserName'] = undefined;

/**
 * @member {String} smtpPassword
 */
EmailSettingsDto.prototype['smtpPassword'] = undefined;

/**
 * @member {String} smtpDomain
 */
EmailSettingsDto.prototype['smtpDomain'] = undefined;

/**
 * @member {Boolean} smtpEnableSsl
 */
EmailSettingsDto.prototype['smtpEnableSsl'] = undefined;

/**
 * @member {Boolean} smtpUseDefaultCredentials
 */
EmailSettingsDto.prototype['smtpUseDefaultCredentials'] = undefined;

/**
 * @member {String} defaultFromAddress
 */
EmailSettingsDto.prototype['defaultFromAddress'] = undefined;

/**
 * @member {String} defaultFromDisplayName
 */
EmailSettingsDto.prototype['defaultFromDisplayName'] = undefined;






export default EmailSettingsDto;

