/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ExtensionPropertyDto from './ExtensionPropertyDto';

/**
 * The EntityExtensionDto model module.
 * @module model/EntityExtensionDto
 * @version v1
 */
class EntityExtensionDto {
    /**
     * Constructs a new <code>EntityExtensionDto</code>.
     * @alias module:model/EntityExtensionDto
     */
    constructor() { 
        
        EntityExtensionDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntityExtensionDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntityExtensionDto} obj Optional instance to populate.
     * @return {module:model/EntityExtensionDto} The populated <code>EntityExtensionDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntityExtensionDto();

            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ApiClient.convertToType(data['properties'], {'String': ExtensionPropertyDto});
            }
            if (data.hasOwnProperty('configuration')) {
                obj['configuration'] = ApiClient.convertToType(data['configuration'], {'String': Object});
            }
        }
        return obj;
    }


}

/**
 * @member {Object.<String, module:model/ExtensionPropertyDto>} properties
 */
EntityExtensionDto.prototype['properties'] = undefined;

/**
 * @member {Object.<String, Object>} configuration
 */
EntityExtensionDto.prototype['configuration'] = undefined;






export default EntityExtensionDto;

