/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ExtensionPropertyUiFormDto from './ExtensionPropertyUiFormDto';
import ExtensionPropertyUiLookupDto from './ExtensionPropertyUiLookupDto';
import ExtensionPropertyUiTableDto from './ExtensionPropertyUiTableDto';

/**
 * The ExtensionPropertyUiDto model module.
 * @module model/ExtensionPropertyUiDto
 * @version v1
 */
class ExtensionPropertyUiDto {
    /**
     * Constructs a new <code>ExtensionPropertyUiDto</code>.
     * @alias module:model/ExtensionPropertyUiDto
     */
    constructor() { 
        
        ExtensionPropertyUiDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ExtensionPropertyUiDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExtensionPropertyUiDto} obj Optional instance to populate.
     * @return {module:model/ExtensionPropertyUiDto} The populated <code>ExtensionPropertyUiDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExtensionPropertyUiDto();

            if (data.hasOwnProperty('onTable')) {
                obj['onTable'] = ExtensionPropertyUiTableDto.constructFromObject(data['onTable']);
            }
            if (data.hasOwnProperty('onCreateForm')) {
                obj['onCreateForm'] = ExtensionPropertyUiFormDto.constructFromObject(data['onCreateForm']);
            }
            if (data.hasOwnProperty('onEditForm')) {
                obj['onEditForm'] = ExtensionPropertyUiFormDto.constructFromObject(data['onEditForm']);
            }
            if (data.hasOwnProperty('lookup')) {
                obj['lookup'] = ExtensionPropertyUiLookupDto.constructFromObject(data['lookup']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ExtensionPropertyUiTableDto} onTable
 */
ExtensionPropertyUiDto.prototype['onTable'] = undefined;

/**
 * @member {module:model/ExtensionPropertyUiFormDto} onCreateForm
 */
ExtensionPropertyUiDto.prototype['onCreateForm'] = undefined;

/**
 * @member {module:model/ExtensionPropertyUiFormDto} onEditForm
 */
ExtensionPropertyUiDto.prototype['onEditForm'] = undefined;

/**
 * @member {module:model/ExtensionPropertyUiLookupDto} lookup
 */
ExtensionPropertyUiDto.prototype['lookup'] = undefined;






export default ExtensionPropertyUiDto;

