/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ExtensionPropertyUiLookupDto model module.
 * @module model/ExtensionPropertyUiLookupDto
 * @version v1
 */
class ExtensionPropertyUiLookupDto {
    /**
     * Constructs a new <code>ExtensionPropertyUiLookupDto</code>.
     * @alias module:model/ExtensionPropertyUiLookupDto
     */
    constructor() { 
        
        ExtensionPropertyUiLookupDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ExtensionPropertyUiLookupDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExtensionPropertyUiLookupDto} obj Optional instance to populate.
     * @return {module:model/ExtensionPropertyUiLookupDto} The populated <code>ExtensionPropertyUiLookupDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExtensionPropertyUiLookupDto();

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('resultListPropertyName')) {
                obj['resultListPropertyName'] = ApiClient.convertToType(data['resultListPropertyName'], 'String');
            }
            if (data.hasOwnProperty('displayPropertyName')) {
                obj['displayPropertyName'] = ApiClient.convertToType(data['displayPropertyName'], 'String');
            }
            if (data.hasOwnProperty('valuePropertyName')) {
                obj['valuePropertyName'] = ApiClient.convertToType(data['valuePropertyName'], 'String');
            }
            if (data.hasOwnProperty('filterParamName')) {
                obj['filterParamName'] = ApiClient.convertToType(data['filterParamName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} url
 */
ExtensionPropertyUiLookupDto.prototype['url'] = undefined;

/**
 * @member {String} resultListPropertyName
 */
ExtensionPropertyUiLookupDto.prototype['resultListPropertyName'] = undefined;

/**
 * @member {String} displayPropertyName
 */
ExtensionPropertyUiLookupDto.prototype['displayPropertyName'] = undefined;

/**
 * @member {String} valuePropertyName
 */
ExtensionPropertyUiLookupDto.prototype['valuePropertyName'] = undefined;

/**
 * @member {String} filterParamName
 */
ExtensionPropertyUiLookupDto.prototype['filterParamName'] = undefined;






export default ExtensionPropertyUiLookupDto;

