/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ExtensionEnumFieldDto from './ExtensionEnumFieldDto';

/**
 * The ExtensionEnumDto model module.
 * @module model/ExtensionEnumDto
 * @version v1
 */
class ExtensionEnumDto {
    /**
     * Constructs a new <code>ExtensionEnumDto</code>.
     * @alias module:model/ExtensionEnumDto
     */
    constructor() { 
        
        ExtensionEnumDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ExtensionEnumDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExtensionEnumDto} obj Optional instance to populate.
     * @return {module:model/ExtensionEnumDto} The populated <code>ExtensionEnumDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExtensionEnumDto();

            if (data.hasOwnProperty('fields')) {
                obj['fields'] = ApiClient.convertToType(data['fields'], [ExtensionEnumFieldDto]);
            }
            if (data.hasOwnProperty('localizationResource')) {
                obj['localizationResource'] = ApiClient.convertToType(data['localizationResource'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/ExtensionEnumFieldDto>} fields
 */
ExtensionEnumDto.prototype['fields'] = undefined;

/**
 * @member {String} localizationResource
 */
ExtensionEnumDto.prototype['localizationResource'] = undefined;






export default ExtensionEnumDto;

