/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FindTenantResultDto model module.
 * @module model/FindTenantResultDto
 * @version v1
 */
class FindTenantResultDto {
    /**
     * Constructs a new <code>FindTenantResultDto</code>.
     * @alias module:model/FindTenantResultDto
     */
    constructor() { 
        
        FindTenantResultDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FindTenantResultDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FindTenantResultDto} obj Optional instance to populate.
     * @return {module:model/FindTenantResultDto} The populated <code>FindTenantResultDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FindTenantResultDto();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('tenantId')) {
                obj['tenantId'] = ApiClient.convertToType(data['tenantId'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('isActive')) {
                obj['isActive'] = ApiClient.convertToType(data['isActive'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} success
 */
FindTenantResultDto.prototype['success'] = undefined;

/**
 * @member {String} tenantId
 */
FindTenantResultDto.prototype['tenantId'] = undefined;

/**
 * @member {String} name
 */
FindTenantResultDto.prototype['name'] = undefined;

/**
 * @member {Boolean} isActive
 */
FindTenantResultDto.prototype['isActive'] = undefined;






export default FindTenantResultDto;

