/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FeatureGroupDto from './FeatureGroupDto';

/**
 * The GetFeatureListResultDto model module.
 * @module model/GetFeatureListResultDto
 * @version v1
 */
class GetFeatureListResultDto {
    /**
     * Constructs a new <code>GetFeatureListResultDto</code>.
     * @alias module:model/GetFeatureListResultDto
     */
    constructor() { 
        
        GetFeatureListResultDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetFeatureListResultDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetFeatureListResultDto} obj Optional instance to populate.
     * @return {module:model/GetFeatureListResultDto} The populated <code>GetFeatureListResultDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetFeatureListResultDto();

            if (data.hasOwnProperty('groups')) {
                obj['groups'] = ApiClient.convertToType(data['groups'], [FeatureGroupDto]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/FeatureGroupDto>} groups
 */
GetFeatureListResultDto.prototype['groups'] = undefined;






export default GetFeatureListResultDto;

