/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PermissionGroupDto from './PermissionGroupDto';

/**
 * The GetPermissionListResultDto model module.
 * @module model/GetPermissionListResultDto
 * @version v1
 */
class GetPermissionListResultDto {
    /**
     * Constructs a new <code>GetPermissionListResultDto</code>.
     * @alias module:model/GetPermissionListResultDto
     */
    constructor() { 
        
        GetPermissionListResultDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetPermissionListResultDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetPermissionListResultDto} obj Optional instance to populate.
     * @return {module:model/GetPermissionListResultDto} The populated <code>GetPermissionListResultDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetPermissionListResultDto();

            if (data.hasOwnProperty('entityDisplayName')) {
                obj['entityDisplayName'] = ApiClient.convertToType(data['entityDisplayName'], 'String');
            }
            if (data.hasOwnProperty('groups')) {
                obj['groups'] = ApiClient.convertToType(data['groups'], [PermissionGroupDto]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} entityDisplayName
 */
GetPermissionListResultDto.prototype['entityDisplayName'] = undefined;

/**
 * @member {Array.<module:model/PermissionGroupDto>} groups
 */
GetPermissionListResultDto.prototype['groups'] = undefined;






export default GetPermissionListResultDto;

