/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IdentityUserUpdateDto model module.
 * @module model/IdentityUserUpdateDto
 * @version v1
 */
class IdentityUserUpdateDto {
    /**
     * Constructs a new <code>IdentityUserUpdateDto</code>.
     * @alias module:model/IdentityUserUpdateDto
     * @param userName {String} 
     * @param email {String} 
     */
    constructor(userName, email) { 
        
        IdentityUserUpdateDto.initialize(this, userName, email);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, userName, email) { 
        obj['userName'] = userName;
        obj['email'] = email;
    }

    /**
     * Constructs a <code>IdentityUserUpdateDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IdentityUserUpdateDto} obj Optional instance to populate.
     * @return {module:model/IdentityUserUpdateDto} The populated <code>IdentityUserUpdateDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IdentityUserUpdateDto();

            if (data.hasOwnProperty('extraProperties')) {
                obj['extraProperties'] = ApiClient.convertToType(data['extraProperties'], {'String': Object});
            }
            if (data.hasOwnProperty('userName')) {
                obj['userName'] = ApiClient.convertToType(data['userName'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('surname')) {
                obj['surname'] = ApiClient.convertToType(data['surname'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('phoneNumber')) {
                obj['phoneNumber'] = ApiClient.convertToType(data['phoneNumber'], 'String');
            }
            if (data.hasOwnProperty('isActive')) {
                obj['isActive'] = ApiClient.convertToType(data['isActive'], 'Boolean');
            }
            if (data.hasOwnProperty('lockoutEnabled')) {
                obj['lockoutEnabled'] = ApiClient.convertToType(data['lockoutEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('roleNames')) {
                obj['roleNames'] = ApiClient.convertToType(data['roleNames'], ['String']);
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('concurrencyStamp')) {
                obj['concurrencyStamp'] = ApiClient.convertToType(data['concurrencyStamp'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Object.<String, Object>} extraProperties
 */
IdentityUserUpdateDto.prototype['extraProperties'] = undefined;

/**
 * @member {String} userName
 */
IdentityUserUpdateDto.prototype['userName'] = undefined;

/**
 * @member {String} name
 */
IdentityUserUpdateDto.prototype['name'] = undefined;

/**
 * @member {String} surname
 */
IdentityUserUpdateDto.prototype['surname'] = undefined;

/**
 * @member {String} email
 */
IdentityUserUpdateDto.prototype['email'] = undefined;

/**
 * @member {String} phoneNumber
 */
IdentityUserUpdateDto.prototype['phoneNumber'] = undefined;

/**
 * @member {Boolean} isActive
 */
IdentityUserUpdateDto.prototype['isActive'] = undefined;

/**
 * @member {Boolean} lockoutEnabled
 */
IdentityUserUpdateDto.prototype['lockoutEnabled'] = undefined;

/**
 * @member {Array.<String>} roleNames
 */
IdentityUserUpdateDto.prototype['roleNames'] = undefined;

/**
 * @member {String} password
 */
IdentityUserUpdateDto.prototype['password'] = undefined;

/**
 * @member {String} concurrencyStamp
 */
IdentityUserUpdateDto.prototype['concurrencyStamp'] = undefined;






export default IdentityUserUpdateDto;

