/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IdentityUserDto model module.
 * @module model/IdentityUserDto
 * @version v1
 */
class IdentityUserDto {
    /**
     * Constructs a new <code>IdentityUserDto</code>.
     * @alias module:model/IdentityUserDto
     */
    constructor() { 
        
        IdentityUserDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IdentityUserDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IdentityUserDto} obj Optional instance to populate.
     * @return {module:model/IdentityUserDto} The populated <code>IdentityUserDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IdentityUserDto();

            if (data.hasOwnProperty('extraProperties')) {
                obj['extraProperties'] = ApiClient.convertToType(data['extraProperties'], {'String': Object});
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('creationTime')) {
                obj['creationTime'] = ApiClient.convertToType(data['creationTime'], 'Date');
            }
            if (data.hasOwnProperty('creatorId')) {
                obj['creatorId'] = ApiClient.convertToType(data['creatorId'], 'String');
            }
            if (data.hasOwnProperty('lastModificationTime')) {
                obj['lastModificationTime'] = ApiClient.convertToType(data['lastModificationTime'], 'Date');
            }
            if (data.hasOwnProperty('lastModifierId')) {
                obj['lastModifierId'] = ApiClient.convertToType(data['lastModifierId'], 'String');
            }
            if (data.hasOwnProperty('isDeleted')) {
                obj['isDeleted'] = ApiClient.convertToType(data['isDeleted'], 'Boolean');
            }
            if (data.hasOwnProperty('deleterId')) {
                obj['deleterId'] = ApiClient.convertToType(data['deleterId'], 'String');
            }
            if (data.hasOwnProperty('deletionTime')) {
                obj['deletionTime'] = ApiClient.convertToType(data['deletionTime'], 'Date');
            }
            if (data.hasOwnProperty('tenantId')) {
                obj['tenantId'] = ApiClient.convertToType(data['tenantId'], 'String');
            }
            if (data.hasOwnProperty('userName')) {
                obj['userName'] = ApiClient.convertToType(data['userName'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('surname')) {
                obj['surname'] = ApiClient.convertToType(data['surname'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('emailConfirmed')) {
                obj['emailConfirmed'] = ApiClient.convertToType(data['emailConfirmed'], 'Boolean');
            }
            if (data.hasOwnProperty('phoneNumber')) {
                obj['phoneNumber'] = ApiClient.convertToType(data['phoneNumber'], 'String');
            }
            if (data.hasOwnProperty('phoneNumberConfirmed')) {
                obj['phoneNumberConfirmed'] = ApiClient.convertToType(data['phoneNumberConfirmed'], 'Boolean');
            }
            if (data.hasOwnProperty('isActive')) {
                obj['isActive'] = ApiClient.convertToType(data['isActive'], 'Boolean');
            }
            if (data.hasOwnProperty('lockoutEnabled')) {
                obj['lockoutEnabled'] = ApiClient.convertToType(data['lockoutEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('lockoutEnd')) {
                obj['lockoutEnd'] = ApiClient.convertToType(data['lockoutEnd'], 'Date');
            }
            if (data.hasOwnProperty('concurrencyStamp')) {
                obj['concurrencyStamp'] = ApiClient.convertToType(data['concurrencyStamp'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Object.<String, Object>} extraProperties
 */
IdentityUserDto.prototype['extraProperties'] = undefined;

/**
 * @member {String} id
 */
IdentityUserDto.prototype['id'] = undefined;

/**
 * @member {Date} creationTime
 */
IdentityUserDto.prototype['creationTime'] = undefined;

/**
 * @member {String} creatorId
 */
IdentityUserDto.prototype['creatorId'] = undefined;

/**
 * @member {Date} lastModificationTime
 */
IdentityUserDto.prototype['lastModificationTime'] = undefined;

/**
 * @member {String} lastModifierId
 */
IdentityUserDto.prototype['lastModifierId'] = undefined;

/**
 * @member {Boolean} isDeleted
 */
IdentityUserDto.prototype['isDeleted'] = undefined;

/**
 * @member {String} deleterId
 */
IdentityUserDto.prototype['deleterId'] = undefined;

/**
 * @member {Date} deletionTime
 */
IdentityUserDto.prototype['deletionTime'] = undefined;

/**
 * @member {String} tenantId
 */
IdentityUserDto.prototype['tenantId'] = undefined;

/**
 * @member {String} userName
 */
IdentityUserDto.prototype['userName'] = undefined;

/**
 * @member {String} name
 */
IdentityUserDto.prototype['name'] = undefined;

/**
 * @member {String} surname
 */
IdentityUserDto.prototype['surname'] = undefined;

/**
 * @member {String} email
 */
IdentityUserDto.prototype['email'] = undefined;

/**
 * @member {Boolean} emailConfirmed
 */
IdentityUserDto.prototype['emailConfirmed'] = undefined;

/**
 * @member {String} phoneNumber
 */
IdentityUserDto.prototype['phoneNumber'] = undefined;

/**
 * @member {Boolean} phoneNumberConfirmed
 */
IdentityUserDto.prototype['phoneNumberConfirmed'] = undefined;

/**
 * @member {Boolean} isActive
 */
IdentityUserDto.prototype['isActive'] = undefined;

/**
 * @member {Boolean} lockoutEnabled
 */
IdentityUserDto.prototype['lockoutEnabled'] = undefined;

/**
 * @member {Date} lockoutEnd
 */
IdentityUserDto.prototype['lockoutEnd'] = undefined;

/**
 * @member {String} concurrencyStamp
 */
IdentityUserDto.prototype['concurrencyStamp'] = undefined;






export default IdentityUserDto;

