/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IdentityRoleUpdateDto model module.
 * @module model/IdentityRoleUpdateDto
 * @version v1
 */
class IdentityRoleUpdateDto {
    /**
     * Constructs a new <code>IdentityRoleUpdateDto</code>.
     * @alias module:model/IdentityRoleUpdateDto
     * @param name {String} 
     */
    constructor(name) { 
        
        IdentityRoleUpdateDto.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>IdentityRoleUpdateDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IdentityRoleUpdateDto} obj Optional instance to populate.
     * @return {module:model/IdentityRoleUpdateDto} The populated <code>IdentityRoleUpdateDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IdentityRoleUpdateDto();

            if (data.hasOwnProperty('extraProperties')) {
                obj['extraProperties'] = ApiClient.convertToType(data['extraProperties'], {'String': Object});
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('isDefault')) {
                obj['isDefault'] = ApiClient.convertToType(data['isDefault'], 'Boolean');
            }
            if (data.hasOwnProperty('isPublic')) {
                obj['isPublic'] = ApiClient.convertToType(data['isPublic'], 'Boolean');
            }
            if (data.hasOwnProperty('concurrencyStamp')) {
                obj['concurrencyStamp'] = ApiClient.convertToType(data['concurrencyStamp'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Object.<String, Object>} extraProperties
 */
IdentityRoleUpdateDto.prototype['extraProperties'] = undefined;

/**
 * @member {String} name
 */
IdentityRoleUpdateDto.prototype['name'] = undefined;

/**
 * @member {Boolean} isDefault
 */
IdentityRoleUpdateDto.prototype['isDefault'] = undefined;

/**
 * @member {Boolean} isPublic
 */
IdentityRoleUpdateDto.prototype['isPublic'] = undefined;

/**
 * @member {String} concurrencyStamp
 */
IdentityRoleUpdateDto.prototype['concurrencyStamp'] = undefined;






export default IdentityRoleUpdateDto;

