/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IdentityRoleDto model module.
 * @module model/IdentityRoleDto
 * @version v1
 */
class IdentityRoleDto {
    /**
     * Constructs a new <code>IdentityRoleDto</code>.
     * @alias module:model/IdentityRoleDto
     */
    constructor() { 
        
        IdentityRoleDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IdentityRoleDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IdentityRoleDto} obj Optional instance to populate.
     * @return {module:model/IdentityRoleDto} The populated <code>IdentityRoleDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IdentityRoleDto();

            if (data.hasOwnProperty('extraProperties')) {
                obj['extraProperties'] = ApiClient.convertToType(data['extraProperties'], {'String': Object});
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('isDefault')) {
                obj['isDefault'] = ApiClient.convertToType(data['isDefault'], 'Boolean');
            }
            if (data.hasOwnProperty('isStatic')) {
                obj['isStatic'] = ApiClient.convertToType(data['isStatic'], 'Boolean');
            }
            if (data.hasOwnProperty('isPublic')) {
                obj['isPublic'] = ApiClient.convertToType(data['isPublic'], 'Boolean');
            }
            if (data.hasOwnProperty('concurrencyStamp')) {
                obj['concurrencyStamp'] = ApiClient.convertToType(data['concurrencyStamp'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Object.<String, Object>} extraProperties
 */
IdentityRoleDto.prototype['extraProperties'] = undefined;

/**
 * @member {String} id
 */
IdentityRoleDto.prototype['id'] = undefined;

/**
 * @member {String} name
 */
IdentityRoleDto.prototype['name'] = undefined;

/**
 * @member {Boolean} isDefault
 */
IdentityRoleDto.prototype['isDefault'] = undefined;

/**
 * @member {Boolean} isStatic
 */
IdentityRoleDto.prototype['isStatic'] = undefined;

/**
 * @member {Boolean} isPublic
 */
IdentityRoleDto.prototype['isPublic'] = undefined;

/**
 * @member {String} concurrencyStamp
 */
IdentityRoleDto.prototype['concurrencyStamp'] = undefined;






export default IdentityRoleDto;

