/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IdentityUserCreateDto model module.
 * @module model/IdentityUserCreateDto
 * @version v1
 */
class IdentityUserCreateDto {
    /**
     * Constructs a new <code>IdentityUserCreateDto</code>.
     * @alias module:model/IdentityUserCreateDto
     * @param userName {String} 
     * @param email {String} 
     * @param password {String} 
     */
    constructor(userName, email, password) { 
        
        IdentityUserCreateDto.initialize(this, userName, email, password);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, userName, email, password) { 
        obj['userName'] = userName;
        obj['email'] = email;
        obj['password'] = password;
    }

    /**
     * Constructs a <code>IdentityUserCreateDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IdentityUserCreateDto} obj Optional instance to populate.
     * @return {module:model/IdentityUserCreateDto} The populated <code>IdentityUserCreateDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IdentityUserCreateDto();

            if (data.hasOwnProperty('extraProperties')) {
                obj['extraProperties'] = ApiClient.convertToType(data['extraProperties'], {'String': Object});
            }
            if (data.hasOwnProperty('userName')) {
                obj['userName'] = ApiClient.convertToType(data['userName'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('surname')) {
                obj['surname'] = ApiClient.convertToType(data['surname'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('phoneNumber')) {
                obj['phoneNumber'] = ApiClient.convertToType(data['phoneNumber'], 'String');
            }
            if (data.hasOwnProperty('isActive')) {
                obj['isActive'] = ApiClient.convertToType(data['isActive'], 'Boolean');
            }
            if (data.hasOwnProperty('lockoutEnabled')) {
                obj['lockoutEnabled'] = ApiClient.convertToType(data['lockoutEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('roleNames')) {
                obj['roleNames'] = ApiClient.convertToType(data['roleNames'], ['String']);
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Object.<String, Object>} extraProperties
 */
IdentityUserCreateDto.prototype['extraProperties'] = undefined;

/**
 * @member {String} userName
 */
IdentityUserCreateDto.prototype['userName'] = undefined;

/**
 * @member {String} name
 */
IdentityUserCreateDto.prototype['name'] = undefined;

/**
 * @member {String} surname
 */
IdentityUserCreateDto.prototype['surname'] = undefined;

/**
 * @member {String} email
 */
IdentityUserCreateDto.prototype['email'] = undefined;

/**
 * @member {String} phoneNumber
 */
IdentityUserCreateDto.prototype['phoneNumber'] = undefined;

/**
 * @member {Boolean} isActive
 */
IdentityUserCreateDto.prototype['isActive'] = undefined;

/**
 * @member {Boolean} lockoutEnabled
 */
IdentityUserCreateDto.prototype['lockoutEnabled'] = undefined;

/**
 * @member {Array.<String>} roleNames
 */
IdentityUserCreateDto.prototype['roleNames'] = undefined;

/**
 * @member {String} password
 */
IdentityUserCreateDto.prototype['password'] = undefined;






export default IdentityUserCreateDto;

