/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LanguageInfo model module.
 * @module model/LanguageInfo
 * @version v1
 */
class LanguageInfo {
    /**
     * Constructs a new <code>LanguageInfo</code>.
     * @alias module:model/LanguageInfo
     */
    constructor() { 
        
        LanguageInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LanguageInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LanguageInfo} obj Optional instance to populate.
     * @return {module:model/LanguageInfo} The populated <code>LanguageInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LanguageInfo();

            if (data.hasOwnProperty('cultureName')) {
                obj['cultureName'] = ApiClient.convertToType(data['cultureName'], 'String');
            }
            if (data.hasOwnProperty('uiCultureName')) {
                obj['uiCultureName'] = ApiClient.convertToType(data['uiCultureName'], 'String');
            }
            if (data.hasOwnProperty('displayName')) {
                obj['displayName'] = ApiClient.convertToType(data['displayName'], 'String');
            }
            if (data.hasOwnProperty('flagIcon')) {
                obj['flagIcon'] = ApiClient.convertToType(data['flagIcon'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} cultureName
 */
LanguageInfo.prototype['cultureName'] = undefined;

/**
 * @member {String} uiCultureName
 */
LanguageInfo.prototype['uiCultureName'] = undefined;

/**
 * @member {String} displayName
 */
LanguageInfo.prototype['displayName'] = undefined;

/**
 * @member {String} flagIcon
 */
LanguageInfo.prototype['flagIcon'] = undefined;






export default LanguageInfo;

