/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IdentityRoleDto from './IdentityRoleDto';

/**
 * The ListResultDtoOfIdentityRoleDto model module.
 * @module model/ListResultDtoOfIdentityRoleDto
 * @version v1
 */
class ListResultDtoOfIdentityRoleDto {
    /**
     * Constructs a new <code>ListResultDtoOfIdentityRoleDto</code>.
     * @alias module:model/ListResultDtoOfIdentityRoleDto
     */
    constructor() { 
        
        ListResultDtoOfIdentityRoleDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListResultDtoOfIdentityRoleDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListResultDtoOfIdentityRoleDto} obj Optional instance to populate.
     * @return {module:model/ListResultDtoOfIdentityRoleDto} The populated <code>ListResultDtoOfIdentityRoleDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListResultDtoOfIdentityRoleDto();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [IdentityRoleDto]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/IdentityRoleDto>} items
 */
ListResultDtoOfIdentityRoleDto.prototype['items'] = undefined;






export default ListResultDtoOfIdentityRoleDto;

