/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UserData from './UserData';

/**
 * The ListResultDtoOfUserData model module.
 * @module model/ListResultDtoOfUserData
 * @version v1
 */
class ListResultDtoOfUserData {
    /**
     * Constructs a new <code>ListResultDtoOfUserData</code>.
     * @alias module:model/ListResultDtoOfUserData
     */
    constructor() { 
        
        ListResultDtoOfUserData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListResultDtoOfUserData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListResultDtoOfUserData} obj Optional instance to populate.
     * @return {module:model/ListResultDtoOfUserData} The populated <code>ListResultDtoOfUserData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListResultDtoOfUserData();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [UserData]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/UserData>} items
 */
ListResultDtoOfUserData.prototype['items'] = undefined;






export default ListResultDtoOfUserData;

