/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LocalizableStringDto model module.
 * @module model/LocalizableStringDto
 * @version v1
 */
class LocalizableStringDto {
    /**
     * Constructs a new <code>LocalizableStringDto</code>.
     * @alias module:model/LocalizableStringDto
     */
    constructor() { 
        
        LocalizableStringDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LocalizableStringDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LocalizableStringDto} obj Optional instance to populate.
     * @return {module:model/LocalizableStringDto} The populated <code>LocalizableStringDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LocalizableStringDto();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('resource')) {
                obj['resource'] = ApiClient.convertToType(data['resource'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
LocalizableStringDto.prototype['name'] = undefined;

/**
 * @member {String} resource
 */
LocalizableStringDto.prototype['resource'] = undefined;






export default LocalizableStringDto;

