/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MethodParameterApiDescriptionModel model module.
 * @module model/MethodParameterApiDescriptionModel
 * @version v1
 */
class MethodParameterApiDescriptionModel {
    /**
     * Constructs a new <code>MethodParameterApiDescriptionModel</code>.
     * @alias module:model/MethodParameterApiDescriptionModel
     */
    constructor() { 
        
        MethodParameterApiDescriptionModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MethodParameterApiDescriptionModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MethodParameterApiDescriptionModel} obj Optional instance to populate.
     * @return {module:model/MethodParameterApiDescriptionModel} The populated <code>MethodParameterApiDescriptionModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MethodParameterApiDescriptionModel();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('typeAsString')) {
                obj['typeAsString'] = ApiClient.convertToType(data['typeAsString'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('typeSimple')) {
                obj['typeSimple'] = ApiClient.convertToType(data['typeSimple'], 'String');
            }
            if (data.hasOwnProperty('isOptional')) {
                obj['isOptional'] = ApiClient.convertToType(data['isOptional'], 'Boolean');
            }
            if (data.hasOwnProperty('defaultValue')) {
                obj['defaultValue'] = ApiClient.convertToType(data['defaultValue'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
MethodParameterApiDescriptionModel.prototype['name'] = undefined;

/**
 * @member {String} typeAsString
 */
MethodParameterApiDescriptionModel.prototype['typeAsString'] = undefined;

/**
 * @member {String} type
 */
MethodParameterApiDescriptionModel.prototype['type'] = undefined;

/**
 * @member {String} typeSimple
 */
MethodParameterApiDescriptionModel.prototype['typeSimple'] = undefined;

/**
 * @member {Boolean} isOptional
 */
MethodParameterApiDescriptionModel.prototype['isOptional'] = undefined;

/**
 * @member {Object} defaultValue
 */
MethodParameterApiDescriptionModel.prototype['defaultValue'] = undefined;






export default MethodParameterApiDescriptionModel;

