/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ControllerApiDescriptionModel from './ControllerApiDescriptionModel';

/**
 * The ModuleApiDescriptionModel model module.
 * @module model/ModuleApiDescriptionModel
 * @version v1
 */
class ModuleApiDescriptionModel {
    /**
     * Constructs a new <code>ModuleApiDescriptionModel</code>.
     * @alias module:model/ModuleApiDescriptionModel
     */
    constructor() { 
        
        ModuleApiDescriptionModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModuleApiDescriptionModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModuleApiDescriptionModel} obj Optional instance to populate.
     * @return {module:model/ModuleApiDescriptionModel} The populated <code>ModuleApiDescriptionModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModuleApiDescriptionModel();

            if (data.hasOwnProperty('rootPath')) {
                obj['rootPath'] = ApiClient.convertToType(data['rootPath'], 'String');
            }
            if (data.hasOwnProperty('remoteServiceName')) {
                obj['remoteServiceName'] = ApiClient.convertToType(data['remoteServiceName'], 'String');
            }
            if (data.hasOwnProperty('controllers')) {
                obj['controllers'] = ApiClient.convertToType(data['controllers'], {'String': ControllerApiDescriptionModel});
            }
        }
        return obj;
    }


}

/**
 * @member {String} rootPath
 */
ModuleApiDescriptionModel.prototype['rootPath'] = undefined;

/**
 * @member {String} remoteServiceName
 */
ModuleApiDescriptionModel.prototype['remoteServiceName'] = undefined;

/**
 * @member {Object.<String, module:model/ControllerApiDescriptionModel>} controllers
 */
ModuleApiDescriptionModel.prototype['controllers'] = undefined;






export default ModuleApiDescriptionModel;

