/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EntityExtensionDto from './EntityExtensionDto';

/**
 * The ModuleExtensionDto model module.
 * @module model/ModuleExtensionDto
 * @version v1
 */
class ModuleExtensionDto {
    /**
     * Constructs a new <code>ModuleExtensionDto</code>.
     * @alias module:model/ModuleExtensionDto
     */
    constructor() { 
        
        ModuleExtensionDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModuleExtensionDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModuleExtensionDto} obj Optional instance to populate.
     * @return {module:model/ModuleExtensionDto} The populated <code>ModuleExtensionDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModuleExtensionDto();

            if (data.hasOwnProperty('entities')) {
                obj['entities'] = ApiClient.convertToType(data['entities'], {'String': EntityExtensionDto});
            }
            if (data.hasOwnProperty('configuration')) {
                obj['configuration'] = ApiClient.convertToType(data['configuration'], {'String': Object});
            }
        }
        return obj;
    }


}

/**
 * @member {Object.<String, module:model/EntityExtensionDto>} entities
 */
ModuleExtensionDto.prototype['entities'] = undefined;

/**
 * @member {Object.<String, Object>} configuration
 */
ModuleExtensionDto.prototype['configuration'] = undefined;






export default ModuleExtensionDto;

