/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MultiTenancyInfoDto model module.
 * @module model/MultiTenancyInfoDto
 * @version v1
 */
class MultiTenancyInfoDto {
    /**
     * Constructs a new <code>MultiTenancyInfoDto</code>.
     * @alias module:model/MultiTenancyInfoDto
     */
    constructor() { 
        
        MultiTenancyInfoDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MultiTenancyInfoDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MultiTenancyInfoDto} obj Optional instance to populate.
     * @return {module:model/MultiTenancyInfoDto} The populated <code>MultiTenancyInfoDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MultiTenancyInfoDto();

            if (data.hasOwnProperty('isEnabled')) {
                obj['isEnabled'] = ApiClient.convertToType(data['isEnabled'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} isEnabled
 */
MultiTenancyInfoDto.prototype['isEnabled'] = undefined;






export default MultiTenancyInfoDto;

