/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ExtensionEnumDto from './ExtensionEnumDto';
import ModuleExtensionDto from './ModuleExtensionDto';

/**
 * The ObjectExtensionsDto model module.
 * @module model/ObjectExtensionsDto
 * @version v1
 */
class ObjectExtensionsDto {
    /**
     * Constructs a new <code>ObjectExtensionsDto</code>.
     * @alias module:model/ObjectExtensionsDto
     */
    constructor() { 
        
        ObjectExtensionsDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ObjectExtensionsDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ObjectExtensionsDto} obj Optional instance to populate.
     * @return {module:model/ObjectExtensionsDto} The populated <code>ObjectExtensionsDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ObjectExtensionsDto();

            if (data.hasOwnProperty('modules')) {
                obj['modules'] = ApiClient.convertToType(data['modules'], {'String': ModuleExtensionDto});
            }
            if (data.hasOwnProperty('enums')) {
                obj['enums'] = ApiClient.convertToType(data['enums'], {'String': ExtensionEnumDto});
            }
        }
        return obj;
    }


}

/**
 * @member {Object.<String, module:model/ModuleExtensionDto>} modules
 */
ObjectExtensionsDto.prototype['modules'] = undefined;

/**
 * @member {Object.<String, module:model/ExtensionEnumDto>} enums
 */
ObjectExtensionsDto.prototype['enums'] = undefined;






export default ObjectExtensionsDto;

