/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PermissionGrantInfoDto from './PermissionGrantInfoDto';

/**
 * The PermissionGroupDto model module.
 * @module model/PermissionGroupDto
 * @version v1
 */
class PermissionGroupDto {
    /**
     * Constructs a new <code>PermissionGroupDto</code>.
     * @alias module:model/PermissionGroupDto
     */
    constructor() { 
        
        PermissionGroupDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PermissionGroupDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PermissionGroupDto} obj Optional instance to populate.
     * @return {module:model/PermissionGroupDto} The populated <code>PermissionGroupDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PermissionGroupDto();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('displayName')) {
                obj['displayName'] = ApiClient.convertToType(data['displayName'], 'String');
            }
            if (data.hasOwnProperty('permissions')) {
                obj['permissions'] = ApiClient.convertToType(data['permissions'], [PermissionGrantInfoDto]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
PermissionGroupDto.prototype['name'] = undefined;

/**
 * @member {String} displayName
 */
PermissionGroupDto.prototype['displayName'] = undefined;

/**
 * @member {Array.<module:model/PermissionGrantInfoDto>} permissions
 */
PermissionGroupDto.prototype['permissions'] = undefined;






export default PermissionGroupDto;

