/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RegisterDto model module.
 * @module model/RegisterDto
 * @version v1
 */
class RegisterDto {
    /**
     * Constructs a new <code>RegisterDto</code>.
     * @alias module:model/RegisterDto
     * @param userName {String} 
     * @param emailAddress {String} 
     * @param password {String} 
     * @param appName {String} 
     */
    constructor(userName, emailAddress, password, appName) { 
        
        RegisterDto.initialize(this, userName, emailAddress, password, appName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, userName, emailAddress, password, appName) { 
        obj['userName'] = userName;
        obj['emailAddress'] = emailAddress;
        obj['password'] = password;
        obj['appName'] = appName;
    }

    /**
     * Constructs a <code>RegisterDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RegisterDto} obj Optional instance to populate.
     * @return {module:model/RegisterDto} The populated <code>RegisterDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RegisterDto();

            if (data.hasOwnProperty('extraProperties')) {
                obj['extraProperties'] = ApiClient.convertToType(data['extraProperties'], {'String': Object});
            }
            if (data.hasOwnProperty('userName')) {
                obj['userName'] = ApiClient.convertToType(data['userName'], 'String');
            }
            if (data.hasOwnProperty('emailAddress')) {
                obj['emailAddress'] = ApiClient.convertToType(data['emailAddress'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('appName')) {
                obj['appName'] = ApiClient.convertToType(data['appName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Object.<String, Object>} extraProperties
 */
RegisterDto.prototype['extraProperties'] = undefined;

/**
 * @member {String} userName
 */
RegisterDto.prototype['userName'] = undefined;

/**
 * @member {String} emailAddress
 */
RegisterDto.prototype['emailAddress'] = undefined;

/**
 * @member {String} password
 */
RegisterDto.prototype['password'] = undefined;

/**
 * @member {String} appName
 */
RegisterDto.prototype['appName'] = undefined;






export default RegisterDto;

