/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RemoteServiceValidationErrorInfo model module.
 * @module model/RemoteServiceValidationErrorInfo
 * @version v1
 */
class RemoteServiceValidationErrorInfo {
    /**
     * Constructs a new <code>RemoteServiceValidationErrorInfo</code>.
     * @alias module:model/RemoteServiceValidationErrorInfo
     */
    constructor() { 
        
        RemoteServiceValidationErrorInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RemoteServiceValidationErrorInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RemoteServiceValidationErrorInfo} obj Optional instance to populate.
     * @return {module:model/RemoteServiceValidationErrorInfo} The populated <code>RemoteServiceValidationErrorInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RemoteServiceValidationErrorInfo();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('members')) {
                obj['members'] = ApiClient.convertToType(data['members'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} message
 */
RemoteServiceValidationErrorInfo.prototype['message'] = undefined;

/**
 * @member {Array.<String>} members
 */
RemoteServiceValidationErrorInfo.prototype['members'] = undefined;






export default RemoteServiceValidationErrorInfo;

