/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RemoteServiceErrorInfo from './RemoteServiceErrorInfo';

/**
 * The RemoteServiceErrorResponse model module.
 * @module model/RemoteServiceErrorResponse
 * @version v1
 */
class RemoteServiceErrorResponse {
    /**
     * Constructs a new <code>RemoteServiceErrorResponse</code>.
     * @alias module:model/RemoteServiceErrorResponse
     */
    constructor() { 
        
        RemoteServiceErrorResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RemoteServiceErrorResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RemoteServiceErrorResponse} obj Optional instance to populate.
     * @return {module:model/RemoteServiceErrorResponse} The populated <code>RemoteServiceErrorResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RemoteServiceErrorResponse();

            if (data.hasOwnProperty('error')) {
                obj['error'] = RemoteServiceErrorInfo.constructFromObject(data['error']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/RemoteServiceErrorInfo} error
 */
RemoteServiceErrorResponse.prototype['error'] = undefined;






export default RemoteServiceErrorResponse;

