/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ResetPasswordDto model module.
 * @module model/ResetPasswordDto
 * @version v1
 */
class ResetPasswordDto {
    /**
     * Constructs a new <code>ResetPasswordDto</code>.
     * @alias module:model/ResetPasswordDto
     * @param resetToken {String} 
     * @param password {String} 
     */
    constructor(resetToken, password) { 
        
        ResetPasswordDto.initialize(this, resetToken, password);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, resetToken, password) { 
        obj['resetToken'] = resetToken;
        obj['password'] = password;
    }

    /**
     * Constructs a <code>ResetPasswordDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResetPasswordDto} obj Optional instance to populate.
     * @return {module:model/ResetPasswordDto} The populated <code>ResetPasswordDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResetPasswordDto();

            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
            if (data.hasOwnProperty('resetToken')) {
                obj['resetToken'] = ApiClient.convertToType(data['resetToken'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} userId
 */
ResetPasswordDto.prototype['userId'] = undefined;

/**
 * @member {String} resetToken
 */
ResetPasswordDto.prototype['resetToken'] = undefined;

/**
 * @member {String} password
 */
ResetPasswordDto.prototype['password'] = undefined;






export default ResetPasswordDto;

