/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ReturnValueApiDescriptionModel model module.
 * @module model/ReturnValueApiDescriptionModel
 * @version v1
 */
class ReturnValueApiDescriptionModel {
    /**
     * Constructs a new <code>ReturnValueApiDescriptionModel</code>.
     * @alias module:model/ReturnValueApiDescriptionModel
     */
    constructor() { 
        
        ReturnValueApiDescriptionModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReturnValueApiDescriptionModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReturnValueApiDescriptionModel} obj Optional instance to populate.
     * @return {module:model/ReturnValueApiDescriptionModel} The populated <code>ReturnValueApiDescriptionModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReturnValueApiDescriptionModel();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('typeSimple')) {
                obj['typeSimple'] = ApiClient.convertToType(data['typeSimple'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} type
 */
ReturnValueApiDescriptionModel.prototype['type'] = undefined;

/**
 * @member {String} typeSimple
 */
ReturnValueApiDescriptionModel.prototype['typeSimple'] = undefined;






export default ReturnValueApiDescriptionModel;

