/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SendTestEmailInput model module.
 * @module model/SendTestEmailInput
 * @version v1
 */
class SendTestEmailInput {
    /**
     * Constructs a new <code>SendTestEmailInput</code>.
     * @alias module:model/SendTestEmailInput
     * @param senderEmailAddress {String} 
     * @param targetEmailAddress {String} 
     * @param subject {String} 
     */
    constructor(senderEmailAddress, targetEmailAddress, subject) { 
        
        SendTestEmailInput.initialize(this, senderEmailAddress, targetEmailAddress, subject);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, senderEmailAddress, targetEmailAddress, subject) { 
        obj['senderEmailAddress'] = senderEmailAddress;
        obj['targetEmailAddress'] = targetEmailAddress;
        obj['subject'] = subject;
    }

    /**
     * Constructs a <code>SendTestEmailInput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendTestEmailInput} obj Optional instance to populate.
     * @return {module:model/SendTestEmailInput} The populated <code>SendTestEmailInput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendTestEmailInput();

            if (data.hasOwnProperty('senderEmailAddress')) {
                obj['senderEmailAddress'] = ApiClient.convertToType(data['senderEmailAddress'], 'String');
            }
            if (data.hasOwnProperty('targetEmailAddress')) {
                obj['targetEmailAddress'] = ApiClient.convertToType(data['targetEmailAddress'], 'String');
            }
            if (data.hasOwnProperty('subject')) {
                obj['subject'] = ApiClient.convertToType(data['subject'], 'String');
            }
            if (data.hasOwnProperty('body')) {
                obj['body'] = ApiClient.convertToType(data['body'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} senderEmailAddress
 */
SendTestEmailInput.prototype['senderEmailAddress'] = undefined;

/**
 * @member {String} targetEmailAddress
 */
SendTestEmailInput.prototype['targetEmailAddress'] = undefined;

/**
 * @member {String} subject
 */
SendTestEmailInput.prototype['subject'] = undefined;

/**
 * @member {String} body
 */
SendTestEmailInput.prototype['body'] = undefined;






export default SendTestEmailInput;

