/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SendPasswordResetCodeDto model module.
 * @module model/SendPasswordResetCodeDto
 * @version v1
 */
class SendPasswordResetCodeDto {
    /**
     * Constructs a new <code>SendPasswordResetCodeDto</code>.
     * @alias module:model/SendPasswordResetCodeDto
     * @param email {String} 
     * @param appName {String} 
     */
    constructor(email, appName) { 
        
        SendPasswordResetCodeDto.initialize(this, email, appName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, appName) { 
        obj['email'] = email;
        obj['appName'] = appName;
    }

    /**
     * Constructs a <code>SendPasswordResetCodeDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendPasswordResetCodeDto} obj Optional instance to populate.
     * @return {module:model/SendPasswordResetCodeDto} The populated <code>SendPasswordResetCodeDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendPasswordResetCodeDto();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('appName')) {
                obj['appName'] = ApiClient.convertToType(data['appName'], 'String');
            }
            if (data.hasOwnProperty('returnUrl')) {
                obj['returnUrl'] = ApiClient.convertToType(data['returnUrl'], 'String');
            }
            if (data.hasOwnProperty('returnUrlHash')) {
                obj['returnUrlHash'] = ApiClient.convertToType(data['returnUrlHash'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} email
 */
SendPasswordResetCodeDto.prototype['email'] = undefined;

/**
 * @member {String} appName
 */
SendPasswordResetCodeDto.prototype['appName'] = undefined;

/**
 * @member {String} returnUrl
 */
SendPasswordResetCodeDto.prototype['returnUrl'] = undefined;

/**
 * @member {String} returnUrlHash
 */
SendPasswordResetCodeDto.prototype['returnUrlHash'] = undefined;






export default SendPasswordResetCodeDto;

