/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TenantCreateDto model module.
 * @module model/TenantCreateDto
 * @version v1
 */
class TenantCreateDto {
    /**
     * Constructs a new <code>TenantCreateDto</code>.
     * @alias module:model/TenantCreateDto
     * @param name {String} 
     * @param adminEmailAddress {String} 
     * @param adminPassword {String} 
     */
    constructor(name, adminEmailAddress, adminPassword) { 
        
        TenantCreateDto.initialize(this, name, adminEmailAddress, adminPassword);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, adminEmailAddress, adminPassword) { 
        obj['name'] = name;
        obj['adminEmailAddress'] = adminEmailAddress;
        obj['adminPassword'] = adminPassword;
    }

    /**
     * Constructs a <code>TenantCreateDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TenantCreateDto} obj Optional instance to populate.
     * @return {module:model/TenantCreateDto} The populated <code>TenantCreateDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TenantCreateDto();

            if (data.hasOwnProperty('extraProperties')) {
                obj['extraProperties'] = ApiClient.convertToType(data['extraProperties'], {'String': Object});
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('adminEmailAddress')) {
                obj['adminEmailAddress'] = ApiClient.convertToType(data['adminEmailAddress'], 'String');
            }
            if (data.hasOwnProperty('adminPassword')) {
                obj['adminPassword'] = ApiClient.convertToType(data['adminPassword'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Object.<String, Object>} extraProperties
 */
TenantCreateDto.prototype['extraProperties'] = undefined;

/**
 * @member {String} name
 */
TenantCreateDto.prototype['name'] = undefined;

/**
 * @member {String} adminEmailAddress
 */
TenantCreateDto.prototype['adminEmailAddress'] = undefined;

/**
 * @member {String} adminPassword
 */
TenantCreateDto.prototype['adminPassword'] = undefined;






export default TenantCreateDto;

