/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IanaTimeZone from './IanaTimeZone';
import WindowsTimeZone from './WindowsTimeZone';

/**
 * The TimeZone model module.
 * @module model/TimeZone
 * @version v1
 */
class TimeZone {
    /**
     * Constructs a new <code>TimeZone</code>.
     * @alias module:model/TimeZone
     */
    constructor() { 
        
        TimeZone.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TimeZone</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TimeZone} obj Optional instance to populate.
     * @return {module:model/TimeZone} The populated <code>TimeZone</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TimeZone();

            if (data.hasOwnProperty('iana')) {
                obj['iana'] = IanaTimeZone.constructFromObject(data['iana']);
            }
            if (data.hasOwnProperty('windows')) {
                obj['windows'] = WindowsTimeZone.constructFromObject(data['windows']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/IanaTimeZone} iana
 */
TimeZone.prototype['iana'] = undefined;

/**
 * @member {module:model/WindowsTimeZone} windows
 */
TimeZone.prototype['windows'] = undefined;






export default TimeZone;

