/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PropertyApiDescriptionModel from './PropertyApiDescriptionModel';

/**
 * The TypeApiDescriptionModel model module.
 * @module model/TypeApiDescriptionModel
 * @version v1
 */
class TypeApiDescriptionModel {
    /**
     * Constructs a new <code>TypeApiDescriptionModel</code>.
     * @alias module:model/TypeApiDescriptionModel
     */
    constructor() { 
        
        TypeApiDescriptionModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TypeApiDescriptionModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TypeApiDescriptionModel} obj Optional instance to populate.
     * @return {module:model/TypeApiDescriptionModel} The populated <code>TypeApiDescriptionModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TypeApiDescriptionModel();

            if (data.hasOwnProperty('baseType')) {
                obj['baseType'] = ApiClient.convertToType(data['baseType'], 'String');
            }
            if (data.hasOwnProperty('isEnum')) {
                obj['isEnum'] = ApiClient.convertToType(data['isEnum'], 'Boolean');
            }
            if (data.hasOwnProperty('enumNames')) {
                obj['enumNames'] = ApiClient.convertToType(data['enumNames'], ['String']);
            }
            if (data.hasOwnProperty('enumValues')) {
                obj['enumValues'] = ApiClient.convertToType(data['enumValues'], [Object]);
            }
            if (data.hasOwnProperty('genericArguments')) {
                obj['genericArguments'] = ApiClient.convertToType(data['genericArguments'], ['String']);
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ApiClient.convertToType(data['properties'], [PropertyApiDescriptionModel]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} baseType
 */
TypeApiDescriptionModel.prototype['baseType'] = undefined;

/**
 * @member {Boolean} isEnum
 */
TypeApiDescriptionModel.prototype['isEnum'] = undefined;

/**
 * @member {Array.<String>} enumNames
 */
TypeApiDescriptionModel.prototype['enumNames'] = undefined;

/**
 * @member {Array.<Object>} enumValues
 */
TypeApiDescriptionModel.prototype['enumValues'] = undefined;

/**
 * @member {Array.<String>} genericArguments
 */
TypeApiDescriptionModel.prototype['genericArguments'] = undefined;

/**
 * @member {Array.<module:model/PropertyApiDescriptionModel>} properties
 */
TypeApiDescriptionModel.prototype['properties'] = undefined;






export default TypeApiDescriptionModel;

