/**
 * Luna API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UpdateFeatureDto from './UpdateFeatureDto';

/**
 * The UpdateFeaturesDto model module.
 * @module model/UpdateFeaturesDto
 * @version v1
 */
class UpdateFeaturesDto {
    /**
     * Constructs a new <code>UpdateFeaturesDto</code>.
     * @alias module:model/UpdateFeaturesDto
     */
    constructor() { 
        
        UpdateFeaturesDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateFeaturesDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateFeaturesDto} obj Optional instance to populate.
     * @return {module:model/UpdateFeaturesDto} The populated <code>UpdateFeaturesDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateFeaturesDto();

            if (data.hasOwnProperty('features')) {
                obj['features'] = ApiClient.convertToType(data['features'], [UpdateFeatureDto]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/UpdateFeatureDto>} features
 */
UpdateFeaturesDto.prototype['features'] = undefined;






export default UpdateFeaturesDto;

